"""empty message

Revision ID: 2ecf9eb8c451
Revises: cc7bfa617d05
Create Date: 2021-11-05 15:48:34.670081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecf9eb8c451'
down_revision = 'cc7bfa617d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_board_template_timestamp'), 'board_template', ['timestamp'], unique=False)
    op.drop_column('board_template', 'nintervals')
    op.drop_column('board_template', 'points_to_win')
    op.drop_column('board_template', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('duration', sa.DATETIME(), nullable=True))
    op.add_column('board_template', sa.Column('points_to_win', sa.INTEGER(), nullable=True))
    op.add_column('board_template', sa.Column('nintervals', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_board_template_timestamp'), table_name='board_template')
    # ### end Alembic commands ###
