"""empty message

Revision ID: 8833e0c8e7dd
Revises: 2ecf9eb8c451
Create Date: 2021-11-05 15:49:09.936436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8833e0c8e7dd'
down_revision = '2ecf9eb8c451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_template', 'points_to_win')
    op.drop_column('board_template', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('duration', sa.DATETIME(), nullable=True))
    op.add_column('board_template', sa.Column('points_to_win', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
