"""records

Revision ID: 8ac9c34d0cd7
Revises: b61903e39dee
Create Date: 2021-11-05 12:05:26.866976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac9c34d0cd7'
down_revision = 'b61903e39dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team1', sa.String(length=64), nullable=True),
    sa.Column('team2', sa.String(length=64), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_board_timestamp'), 'completed_board', ['timestamp'], unique=False)
    op.drop_index('ix_board_timestamp', table_name='board')
    op.drop_table('board')
    op.add_column('board_template', sa.Column('points_to_win', sa.Integer(), nullable=True))
    op.add_column('board_template', sa.Column('nintervals', sa.Integer(), nullable=True))
    op.add_column('board_template', sa.Column('duration', sa.Interval(), nullable=True))
    op.add_column('board_template', sa.Column('board_view', sa.String(length=140), nullable=True))
    op.drop_index('ix_board_template_timestamp', table_name='board_template')
    op.drop_column('board_template', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_board_template_timestamp', 'board_template', ['timestamp'], unique=False)
    op.drop_column('board_template', 'board_view')
    op.drop_column('board_template', 'duration')
    op.drop_column('board_template', 'nintervals')
    op.drop_column('board_template', 'points_to_win')
    op.create_table('board',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_board_timestamp', 'board', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_completed_board_timestamp'), table_name='completed_board')
    op.drop_table('completed_board')
    # ### end Alembic commands ###
