"""empty message

Revision ID: 919cfd87a3ce
Revises: 8833e0c8e7dd
Create Date: 2021-11-05 15:49:39.019897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919cfd87a3ce'
down_revision = '8833e0c8e7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_template', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('duration', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
