"""empty message

Revision ID: cc7bfa617d05
Revises: 8ac9c34d0cd7
Create Date: 2021-11-05 15:46:19.689143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7bfa617d05'
down_revision = '8ac9c34d0cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('npoints', sa.Integer(), nullable=True))
    op.add_column('board_template', sa.Column('segments', sa.Integer(), nullable=True))
    op.drop_column('board_template', 'timestamp')
    op.drop_column('board_template', 'points_to_win')
    op.drop_column('board_template', 'duration')
    op.drop_column('board_template', 'nintervals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_template', sa.Column('nintervals', sa.INTEGER(), nullable=True))
    op.add_column('board_template', sa.Column('duration', sa.DATETIME(), nullable=True))
    op.add_column('board_template', sa.Column('points_to_win', sa.INTEGER(), nullable=True))
    op.add_column('board_template', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('board_template', 'segments')
    op.drop_column('board_template', 'npoints')
    # ### end Alembic commands ###
